# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    docker:
      - image: circleci/node:14.4-browsers 
    steps:
      - checkout
      - run:
          name: "Step 1 - Install Dependencies"
          command: |
            wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
            mkdir ~/sfdx
            tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1
            sudo ln -sf "$HOME/sfdx/bin/sfdx" "/usr/local/bin/sfdx"
            echo 'y' | sfdx plugins:install isvte-sfdx-plugin
      - run:
          name: "Step 2 - Authenticate to Org"
          command: |
            echo $SFDXURL_INT > /tmp/sfdx_int.url
            sfdx auth:sfdxurl:store -f /tmp/sfdx_int.url -a int_org
      - run:
          name: "Step 3 - Convert to MDAPI format"
          command: |
            sfdx force:source:convert -r force-app/ -d src/
      - run:
          name: "Step 4 - Deploy"
          command: |
            if [[ $CIRCLE_BRANCH == "dev" ]];
            then
              # checkonly to int
              sfdx force:source:deploy -p src/ -c -u int_org
            fi
            if [[ $CIRCLE_BRANCH == "integration" ]];
            then
              # deploy to int
              sfdx force:deploy -p src/ -u int_org
            fi
            
